### ISSUE TITLE
Exercise 2 -- Selecting, Traversing and Manipulation (sandbox.js)

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#1]
This solution can be found in https://github.com/segunadeleye/jqfundamentals/tree/master/exercises/Ex2

**Comment by Shruti2791** [comment]
## Selecting

1) Pt 2: Select the 3rd 'li' element using #myList .
2) Pt 4: 
     a) use chaining.
     b) why are we finding hidden elements on body ? Can't this be directly searched upon jquery object ?
3) Pt 5: use chaining.

## Traversing

1) Pt 2:  You are just finding the parent of that search box. What if the search box is inside another tag element ?
2) Pt 3: Use chaining.
3) Pt 4: We can reduce the number of DOM hits here.
4) Pt 5: Try fetching the first element using jquery selectors.

## Manipulation

1) Pt 1: 
    a) Extra variable '$myList'.
    b) Combine line 88 and 89.
2) Pt 3: Do not use strings to insert html.
3) Pt 4: what if the option list have more options prepended to monday. Fetching with 'eq(2)' will fail.
4) Pt 5: Use chaining.

**Comment by segunadeleye** [comment]
#### FIxed!!!

#### Traversing (Pt 4)

I am not sure of a different way to traverse to the submit button.

**Comment by Shruti2791** [comment]
## Selecting

1) Pt 2: Use #myList only and reach to the 3rd element. Do not use any other id for selecting.

## Traversing

1) Still the same no. of DOM hits. Jquery provides a way to directly select the submit button. Read about it. Ask in case of any doubt.

## Manipulation

1) Pt 3: Do not append to the DOM element twice. Try appending them in one step.
2) Pt 4: Wednesday should come after Tuesday. Why are we appending it to the last of the select drop down ?

**Comment by segunadeleye** [comment]
Issues fixed.

**Comment by Shruti2791** [comment]
looks good :+1:
