### ISSUE TITLE
7.1 Product grid exercise.

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#10]
https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex7/product.js

**Comment by mkangia** [comment]
Segun, functionality its almost everything needed. I am missing ability to do:
'The filters should work together - so I should be able to see Only Yellow products of Brand C which are Available.' . Right now when i cant combine available like other filters. So lets evolve this.
I wonder why we need fetch json on each click. Any particular reason for it?

Plus naming needs some attention. The prototype here is more of a 'ProductList' and not a 'Product'.
Please resubmit

**Comment by segunadeleye** [comment]
I have fixed the issues.

**Comment by mkangia** [comment]
Seems to be working as expected now Segun. In terms of code we can do some improvement. Lets break down the 'filterProducts' method and find a way to implement the logic in the least possible yet simple code.

**Comment by segunadeleye** [comment]
I have made some changes. You can check it now.

**Comment by mkangia** [comment]
You must make an attempt to break some methods segun. Accepting it for now.. But for learning you should definitely spend time on this problem and may be approach it with a fresh approach..
