### ISSUE TITLE
7.2 -- Stack of divs -- on()/delagate exercise.

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#11]
https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex7/stack.js

**Comment by abhishekjain16** [comment]
Both the events of container click should be bind to save method.

Avoid using 'delegate' and 'on' on same id.

**Comment by segunadeleye** [comment]
Issues have been fixed.
