### ISSUE TITLE
Exercise 4.2 -- Add tabbed navigation (tabs.js)

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#3]
Solution in https://github.com/segunadeleye/jqfundamentals/tree/master/exercises/Ex4/tabs.js

**Comment by yuktikhurana** [comment]
1. For last one - showing the first tab, also add the current class to the related &lt;li&gt; element

**Comment by segunadeleye** [comment]
Issues fixed

**Comment by yuktikhurana** [comment]
looks good
