### ISSUE TITLE
Exercise 5.1 -- Reveal hidden text (blog.js)

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#4]
Solution at: https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex5/blog.js

**Comment by abhishekjain16** [comment]
Use Object Oriented approach.

**Comment by abhishekjain16** [comment]
Reduce chaining like:
$(this).parent().siblings().find('p').slideUp();

It is too much DOM dependent.

**Comment by segunadeleye** [comment]
Issues fixed.
