### ISSUE TITLE
5.2 -- Create Drop down menus (navigation.js)

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#5]
Solution at: https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex5/navigation.js

**Comment by Shruti2791** [comment]
1) The #showDropDown method in navigation class is specific to just $('nav li'). Make it generic.

**Comment by Shruti2791** [comment]
use $('nav li') only. Make the changes. I am closing this issue for now
