### ISSUE TITLE
6.2 Load content using JSON

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#9]
Solution at: https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex6/specials.js

**Comment by abhishekjain16** [comment]
1. $div.empty(); is being used on both if else, lets move it outside only if we need to do this.
2. On change every time ajax request is fired, even though same content is needed. Lets try and avoid Ajax request. Load data on page load itself and then use it

**Comment by segunadeleye** [comment]
Issues fixed.

**Comment by abhishekjain16** [comment]
Much better. Only one small concern

this.getList(this.filter);
Why are we sending method name with this. this,filter can be directly called there.

**Comment by segunadeleye** [comment]
It's the callback function that runs after the ajax call returns it's response.

I think I will just store the ajax response in a variable before calling the filter() method on it.

**Comment by segunadeleye** [comment]
Issues fixed
